name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: checkout
        uses: actions/checkout@v3


      - name: build
        id: build
        uses: usimd/pi-gen-action@v1
        with:
          pi-gen-version: arm64
          release: trixie
          image-name: custom
          stage-list: stage0 stage1 stage2 ./stage2-custom
          export-last-stage-only: true
          hostname: pi-custom
          keyboard-keymap: us
          keyboard-layout: English (US)
          locale: en_US.UTF-8
          wpa-country: US
          enable-ssh: 1
          disable-first-boot-user-rename: 1
          username: user
          password: raspberry
          pi-gen-release: Raspberry Pi Custom
          verbose-output: true
          compression: none


      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
