name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

env:
  RELEASE: trixie

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        build:
          - { arch: arm64, branch: arm64 }
          - { arch: armhf, branch: master }
    steps:
      - name: clone pi-gen
        run: |
          git clone --branch "${{ matrix.build.branch }}" --single-branch --depth 1 https://github.com/RPi-Distro/pi-gen.git

      - name: checkout
        uses: actions/checkout@v3
        with:
          path: pi-gen/pi-gen-custom

      - name: generate-config
        run: |
          cat > pi-gen/config <<EOF
          RELEASE=${{ env.RELEASE }}
          IMG_NAME="raspios-custom-${{env.RELEASE}}-${{matrix.build.arch}}"
          LOCALE_DEFAULT=en_US.UTF-8
          TARGET_HOSTNAME=raspberrypi
          KEYBOARD_KEYMAP=us
          KEYBOARD_LAYOUT="English (US)"
          TIMEZONE_DEFAULT=US/Pacific
          FIRST_USER_NAME="${{ secrets.FIRST_USER_NAME }}"
          FIRST_USER_PASS="${{ secrets.FIRST_USER_PASS }}"
          DISABLE_FIRST_BOOT_USER_RENAME=1
          ENABLE_SSH=1
          #PUBKEY_SSH_FIRST_USER="${{ secrets.PUBKEY_SSH_FIRST_USER }}"
          #PUBKEY_ONLY_SSH=1
          WPA_COUNTRY=US     # needed so wifi is not disabled
          USE_QEMU=0
          STAGE_LIST="stage0 stage1 stage2 pi-gen-custom/stage2-custom"
          DEPLOY_COMPRESSION="xz"
          EOF

      - name: build
        run: |
          cd pi-gen
          touch stage2/SKIP_IMAGES
          sudo apt update
          sudo apt install -y quilt qemu-user-static debootstrap libarchive-tools arch-test
          sudo ./build.sh -c config

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: pi-gen/deploy/*.img.xz

      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: info
          path: pi-gen/deploy/*.info
