name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: usimd/pi-gen-action@v1
        with:
          image-name: custom
          stage-list: stage0 stage1 stage2

      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
