name: build

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: usimd/pi-gen-action@v1
        with:
          image-name: test
          stage-list: stage0 stage1 stage2
